import React from "react";
import Icon from "./Icon";

// ─────────────────────────────────────────────────────────────────────────────
// TransactionReceipt — premium styled receipt modal with download.
// ─────────────────────────────────────────────────────────────────────────────

const ACTION_ICONS = { buy: "trending", claim: "bolt", deposit: "coins", listing: "send", cancel: "close" };
const ACTION_COLORS = { buy: "#3b82f6", claim: "#22c55e", deposit: "#f59e0b", listing: "#8b5cf6", cancel: "#ef4444" };

export default function TransactionReceipt({ tx, onClose }) {
  if (!tx) return null;

  const action = tx.action || tx.type || "transaction";
  const amount = Number(tx.amount || 0);
  const date = tx.createdAt ? new Date(tx.createdAt) : new Date();
  const hash = tx.txHash || "—";
  const wallet = tx.from || "—";
  const gas = tx.gasMethod || "eth";
  const propertyId = tx.propertyId || "—";
  const iconName = ACTION_ICONS[action] || "info";
  const accentColor = ACTION_COLORS[action] || "#B9FF66";

  function downloadReceipt() {
    const divider = "═".repeat(50);
    const thin = "─".repeat(50);
    const lines = [
      divider,
      "          REALCHAIN · TRANSACTION RECEIPT",
      divider,
      "",
      `  Date         ${date.toLocaleString("en-IN", { dateStyle: "full", timeStyle: "medium" })}`,
      `  Action       ${action.toUpperCase()}`,
      `  Amount       $${amount.toFixed(6)} USDC`,
      `  Property     #${propertyId}`,
      `  Wallet       ${wallet}`,
      `  Gas Method   ${gas === "ugf" ? "Gasless (UGF)" : "ETH Gas"}`,
      `  Tx Hash      ${hash}`,
      "",
      thin,
      "  This receipt was generated by the RealChain platform.",
      `  Verified on-chain · ${date.toISOString()}`,
      divider,
    ].join("\n");

    const blob = new Blob([lines], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `realchain-receipt-${hash.slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div style={{
      width: 460, maxWidth: "92vw",
      background: "var(--positivus-white, #fff)",
      borderRadius: 20,
      boxShadow: "0 24px 80px rgba(0,0,0,0.25), 0 0 0 1px rgba(0,0,0,0.06)",
      overflow: "hidden",
    }}>
      {/* ── Accent header strip ─────────────────────────────────── */}
      <div style={{
        background: `linear-gradient(135deg, ${accentColor}22, ${accentColor}08)`,
        borderBottom: `1px solid ${accentColor}30`,
        padding: "20px 28px",
        display: "flex", alignItems: "center", justifyContent: "space-between",
      }}>
        <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
          <span style={{
            width: 40, height: 40, display: "inline-flex", alignItems: "center",
            justifyContent: "center", borderRadius: 12,
            background: accentColor, color: "#fff",
            boxShadow: `0 4px 14px ${accentColor}40`,
          }}>
            <Icon name={iconName} size={18} />
          </span>
          <div>
            <div style={{ fontWeight: 800, fontSize: 17, color: "#191A23", letterSpacing: "-0.01em" }}>
              Transaction receipt
            </div>
            <div style={{ fontSize: 12, color: "#666", marginTop: 1 }}>
              {action.charAt(0).toUpperCase() + action.slice(1)} · #{propertyId}
            </div>
          </div>
        </div>
        {onClose && (
          <button onClick={onClose} aria-label="Close" style={{
            width: 32, height: 32, display: "inline-flex", alignItems: "center",
            justifyContent: "center", borderRadius: 10, border: "1px solid #e5e7eb",
            background: "#fff", cursor: "pointer", color: "#666",
            transition: "all 0.15s ease",
          }}
            onMouseOver={(e) => { e.currentTarget.style.background = "#f3f4f6"; }}
            onMouseOut={(e) => { e.currentTarget.style.background = "#fff"; }}
          >
            <Icon name="close" size={12} />
          </button>
        )}
      </div>

      {/* ── Amount hero ─────────────────────────────────────────── */}
      <div style={{
        padding: "24px 28px 20px",
        textAlign: "center",
        borderBottom: "1px solid #f0f0f0",
      }}>
        <div style={{ fontSize: 11, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.08em", color: "#999", marginBottom: 6 }}>
          Amount
        </div>
        <div style={{
          fontSize: 36, fontWeight: 800, letterSpacing: "-0.02em",
          color: accentColor === "#f59e0b" ? "#d97706" : accentColor,
          lineHeight: 1.1,
        }}>
          ${amount.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
        </div>
        <div style={{ fontSize: 12, color: "#999", marginTop: 4 }}>USDC</div>
      </div>

      {/* ── Details grid ───────────────────────────────────────── */}
      <div style={{ padding: "16px 28px 20px" }}>
        <div style={{
          display: "grid", gap: 0,
          borderRadius: 12,
          border: "1px solid #f0f0f0",
          overflow: "hidden",
        }}>
          <DetailRow label="Date" value={date.toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })} icon="clock" />
          <DetailRow label="Wallet" value={`${wallet.slice(0, 8)}…${wallet.slice(-6)}`} icon="users" mono />
          <DetailRow label="Gas method" value={gas === "ugf" ? "Gasless (UGF)" : "ETH"} icon="bolt" badge={gas === "ugf" ? "lime" : "gray"} />
          <DetailRow label="Tx hash" value={`${hash.slice(0, 12)}…${hash.slice(-8)}`} icon="external" mono last />
        </div>
      </div>

      {/* ── Download ───────────────────────────────────────────── */}
      <div style={{ padding: "0 28px 24px" }}>
        <button onClick={downloadReceipt} style={{
          width: "100%", padding: "12px 0",
          borderRadius: 12, border: "none", cursor: "pointer",
          background: "#191A23", color: "#fff",
          fontWeight: 700, fontSize: 14,
          display: "flex", alignItems: "center", justifyContent: "center", gap: 8,
          transition: "opacity 0.15s ease",
        }}
          onMouseOver={(e) => { e.currentTarget.style.opacity = "0.88"; }}
          onMouseOut={(e) => { e.currentTarget.style.opacity = "1"; }}
        >
          <Icon name="download" size={14} />
          Download receipt
        </button>
      </div>
    </div>
  );
}

function DetailRow({ label, value, icon, mono = false, badge, last = false }) {
  return (
    <div style={{
      display: "flex", alignItems: "center", justifyContent: "space-between",
      padding: "11px 16px",
      borderBottom: last ? "none" : "1px solid #f0f0f0",
      background: "#fafafa",
      fontSize: 13,
    }}>
      <span style={{ display: "flex", alignItems: "center", gap: 8, color: "#888" }}>
        <Icon name={icon} size={12} />
        {label}
      </span>
      <span style={{
        fontWeight: 600,
        color: "#191A23",
        fontFamily: mono ? "'JetBrains Mono', 'SF Mono', monospace" : "inherit",
        fontSize: mono ? 11 : 13,
        ...(badge ? {
          padding: "2px 8px", borderRadius: 6,
          background: badge === "lime" ? "#B9FF6620" : "#e5e7eb",
          color: badge === "lime" ? "#4a7c00" : "#666",
          fontSize: 11, fontWeight: 700,
        } : {}),
      }}>
        {value}
      </span>
    </div>
  );
}
